# Generated by Django 5.0.3 on 2024-09-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.BigIntegerField(null=True)),
                ('artcode', models.PositiveBigIntegerField(default=0)),
                ('description', models.CharField(max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('ivatype', models.CharField(max_length=11, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_art_id_c82ff4_idx'), models.Index(fields=['company_id'], name='invoice_art_company_5faba9_idx'), models.Index(fields=['description'], name='invoice_art_descrip_b92c4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon', models.CharField(max_length=111, null=True)),
                ('person_name', models.CharField(max_length=111, null=True)),
                ('cif', models.CharField(max_length=33, null=True, unique=True)),
                ('email', models.CharField(max_length=111, null=True, unique=True)),
                ('emailcompany', models.CharField(max_length=111, null=True)),
                ('password', models.CharField(max_length=111, null=True)),
                ('tlf', models.CharField(max_length=33, null=True)),
                ('tlf2', models.CharField(max_length=33, null=True)),
                ('numvisit', models.BigIntegerField(default=0)),
                ('regtime', models.CharField(max_length=33, null=True)),
                ('lastvisit', models.CharField(max_length=33, null=True)),
                ('uid', models.CharField(max_length=111, null=True)),
                ('country', models.CharField(max_length=33, null=True)),
                ('province', models.CharField(max_length=33, null=True)),
                ('zipcode', models.CharField(max_length=22, null=True)),
                ('city', models.CharField(max_length=33, null=True)),
                ('address', models.CharField(max_length=111, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_com_id_3a34d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=33, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_cou_id_4994ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.BigIntegerField(null=True)),
                ('clientcode', models.PositiveBigIntegerField(default=0)),
                ('cif_nif', models.CharField(max_length=33, null=True)),
                ('razon', models.CharField(max_length=255, null=True)),
                ('person_name', models.CharField(max_length=255, null=True)),
                ('emailcustomer', models.CharField(max_length=111, null=True)),
                ('phone', models.CharField(max_length=33, null=True)),
                ('country', models.CharField(default='España', max_length=111)),
                ('province', models.CharField(max_length=111, null=True)),
                ('zipcode', models.CharField(max_length=11, null=True)),
                ('city', models.CharField(max_length=111, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_cus_id_a48e3c_idx'), models.Index(fields=['company_id'], name='invoice_cus_company_746230_idx'), models.Index(fields=['cif_nif'], name='invoice_cus_cif_nif_720b7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=41, null=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('ejercicio', models.CharField(max_length=7, null=True)),
                ('company_id', models.BigIntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['description'], name='invoice_doc_descrip_02ae73_idx'), models.Index(fields=['company_id'], name='invoice_doc_company_677429_idx'), models.Index(fields=['ejercicio'], name='invoice_doc_ejercic_b75178_idx')],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.BigIntegerField(null=True)),
                ('tipo_factura', models.CharField(max_length=3, null=True)),
                ('ejercicio', models.CharField(max_length=7, null=True)),
                ('serie_fact', models.CharField(max_length=22, null=True)),
                ('numero', models.BigIntegerField(null=True)),
                ('serie_fact_unique', models.CharField(max_length=22, null=True, unique=True)),
                ('customer_id', models.BigIntegerField(null=True)),
                ('customer_num', models.BigIntegerField(null=True)),
                ('receptor_company_name', models.CharField(max_length=222, null=True)),
                ('fecha_expedicion', models.CharField(max_length=33, null=True)),
                ('vencimiento', models.CharField(max_length=33, null=True)),
                ('ivas_desglose', models.CharField(max_length=1000, null=True)),
                ('importe_ivas', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total2', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('observacion', models.CharField(max_length=254, null=True)),
                ('apunta_factura', models.CharField(max_length=22, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='invoice_fac_id_636928_idx'), models.Index(fields=['company_id'], name='invoice_fac_company_4740b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facturalineas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.BigIntegerField(null=True)),
                ('company_id', models.BigIntegerField(null=True)),
                ('serie', models.CharField(max_length=22, null=True)),
                ('article_id', models.BigIntegerField(null=True)),
                ('article_num', models.BigIntegerField(null=True)),
                ('article_name', models.CharField(max_length=254, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('importe_bruto', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('descuento_val', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('importe_con_descuento', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('iva_porcent', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('iva_valor', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('importe_res', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('iva_type', models.CharField(max_length=11, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id'], name='invoice_fac_company_a58809_idx'), models.Index(fields=['invoice_id'], name='invoice_fac_invoice_c8e056_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicledata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.BigIntegerField(null=True)),
                ('company_id', models.BigIntegerField(null=True)),
                ('customer_id', models.BigIntegerField(null=True)),
                ('matricula', models.CharField(max_length=22, null=True)),
                ('other_data', models.CharField(max_length=254, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_id'], name='invoice_veh_invoice_367b29_idx')],
            },
        ),
    ]
