# Generated by Django 5.1 on 2024-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_factura',
            field=models.CharField(max_length=33, null=True),
        ),
    ]
